// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhFG7Qd-HYyxguqVATGSUANusGOtlHRHg',
    appId: '1:992109826517:web:ad5df7a9698f6a47dead5c',
    messagingSenderId: '992109826517',
    projectId: 'appnote-bf6d3',
    authDomain: 'appnote-bf6d3.firebaseapp.com',
    storageBucket: 'appnote-bf6d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkW2cH6Uc3dq_EnwL-vShCaznemrRQ0rk',
    appId: '1:992109826517:android:dac4390cebb92c2cdead5c',
    messagingSenderId: '992109826517',
    projectId: 'appnote-bf6d3',
    storageBucket: 'appnote-bf6d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbiqMO-vajKr60FHSdC5QKEWrlAC7MO6k',
    appId: '1:992109826517:ios:8a3846247b9f8143dead5c',
    messagingSenderId: '992109826517',
    projectId: 'appnote-bf6d3',
    storageBucket: 'appnote-bf6d3.appspot.com',
    iosBundleId: 'com.example.smartNoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbiqMO-vajKr60FHSdC5QKEWrlAC7MO6k',
    appId: '1:992109826517:ios:ca19dfe4e2e65c8ddead5c',
    messagingSenderId: '992109826517',
    projectId: 'appnote-bf6d3',
    storageBucket: 'appnote-bf6d3.appspot.com',
    iosBundleId: 'com.example.smartNoteApp.RunnerTests',
  );
}
